# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/gps/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter gps,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
