# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/telephony-diag/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter telephony-diag,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
