# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/nq-nfc/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/common/nq-nfc

PRODUCT_COPY_FILES += \
    vendor/qcom/common/nq-nfc/proprietary/vendor/bin/nqnfcinfo:$(TARGET_COPY_OUT_VENDOR)/bin/nqnfcinfo
