# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/wlan/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/common/system/wlan

PRODUCT_COPY_FILES += \
    vendor/qcom/common/system/wlan/proprietary/system_ext/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/qcom/common/system/wlan/proprietary/system_ext/lib/vendor.qti.hardware.wigig.supptunnel@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.qti.hardware.wigig.supptunnel@1.0.so \
    vendor/qcom/common/system/wlan/proprietary/system_ext/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/qcom/common/system/wlan/proprietary/system_ext/lib64/vendor.qti.hardware.wigig.supptunnel@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.hardware.wigig.supptunnel@1.0.so

PRODUCT_PACKAGES += \
    vendor.qti.hardware.wigig.netperftuner-V1.0-java \
    vendor.qti.hardware.wigig.supptunnel-V1.0-java
