# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/adreno/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter adreno,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
