# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/audio/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter audio,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
