# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/wfd/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter wfd,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
