# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/alarm/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/qcom/common/system/alarm


PRODUCT_PACKAGES += \
    PowerOffAlarm
