# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/display/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter display,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
