# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/wfd-legacy/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter wfd-legacy,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
