# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/bt/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter bt,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
