# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/qcom/common/system/av/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq (,$(filter av,$(TARGET_COMMON_QTI_COMPONENTS)))

endif
